Feat/update footer market stats
IkigaiLabsETH/ikigailabs.xyz pull request #128
Opened 2024-06-10 12:17 UTC by IkigaiLabsETH

remove link Discord / X in footer and add MarketStats ($BTC/ETH/SOL)

2024-06-10 13:38 UTC, royscheeren requested changes

2024-06-10 13:38 UTC, royscheeren commented on modules/MarketStats/MarketStats.tsx
> +export default MarketStats;
Can you add a new line at the end of the file?

2024-06-10 13:38 UTC, royscheeren commented on modules/MarketStats/index.ts
> +export { default as MarketStats } from './MarketStats';
Same here, new line at the end of the file

2024-06-10 13:38 UTC, royscheeren commented on modules/MarketStats/MarketStats.tsx
> +    fetchPrices();
Would prefer to have this handled by redux, conform to the rest of the app. But it's not interfering with anything. So when the new lines are added I'll leave it up to you to merge or not

2024-06-10 13:42 UTC, IkigaiLabsETH commented on modules/MarketStats/MarketStats.tsx
> +    fetchPrices();
Yeah that was a concern I had bringing axios, how can that be achieved with redux? Think it would indeed be better to stay conform to the rest of the app

2024-06-10 13:44 UTC, IkigaiLabsETH commented on modules/MarketStats/MarketStats.tsx
> +export default MarketStats;
done

2024-06-10 13:44 UTC, IkigaiLabsETH commented on modules/MarketStats/index.ts
> +export { default as MarketStats } from './MarketStats';
done

2024-06-10 13:48 UTC, royscheeren commented on modules/MarketStats/MarketStats.tsx
> +    fetchPrices();
for that you gotta checkout any of the .api.ts files. 

Basically you create an api layer that talks to coingecko, puts the results into redux store and the component can dispatch a request and listen for the result.

2024-06-10 13:53 UTC, IkigaiLabsETH commented on modules/MarketStats/MarketStats.tsx
> +    fetchPrices();
Proposed:

import { createStore, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';
import rootReducer from './reducers';

const store = createStore(rootReducer, applyMiddleware(thunk));

export default store;

---

reducer:

const initialState = {
  btcPrice: 0,
  ethPrice: 0,
  solPrice: 0,
};

const cryptoPricesReducer = (state = initialState, action) => {
  switch (action.type) {
    case 'SET_PRICES':
      return {
        ...state,
        btcPrice: action.payload.btcPrice,
        ethPrice: action.payload.ethPrice,
        solPrice: action.payload.solPrice,
      };
    default:
      return state;
  }
};

export default cryptoPricesReducer;

---

action:


import axios from 'axios';

export const fetchPrices = () => async (dispatch) => {
  try {
    const response = await axios.get('https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,solana&vs_currencies=usd');
    dispatch({
      type: 'SET_PRICES',
      payload: {
        btcPrice: response.data.bitcoin.usd,
        ethPrice: response.data.ethereum.usd,
        solPrice: response.data.solana.usd,
      },
    });
  } catch (error) {
    console.error('Failed to fetch prices:', error);
  }
};

---

module:

import React, { useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { fetchPrices } from '../../actions/cryptoPrices';

const CryptoPrices: React.FC = () => {
  const dispatch = useDispatch();
  const btcPrice = useSelector(state => state.cryptoPrices.btcPrice);
  const ethPrice = useSelector(state => state.cryptoPrices.ethPrice);
  const solPrice = useSelector(state => state.cryptoPrices.solPrice);

  useEffect(() => {
    dispatch(fetchPrices());
  }, [dispatch]);

  return (
    <div className="flex items-center justify-center space-x-4">
      <div>BTC: ${Math.floor(btcPrice)}</div>
      <div>ETH: ${Math.floor(ethPrice)}</div>
      <div>SOL: ${Math.floor(solPrice)}</div>
    </div>
  );
};

export default CryptoPrices;

---

something like this?

2024-06-11 10:56 UTC, royscheeren approved these changes

2024-06-11 11:44 UTC, merged